name: Auto-Release on version bump
on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.8"
                  architecture: "x64"
                  fetch-depth: 0

            - uses: dorny/paths-filter@v2
              id: new
              with:
                  filters: |
                      init:
                        - 'backup/__init__.py'

            - id: version
              run: |
                  version=$(python -c "import backup; print(backup.VERSION)")
                  echo "::set-output name=VERSION::$version"

            - name: Get Commits since last release
              id: changes
              uses: simbo/changes-since-last-release-action@v1

            - name: Display changes since last release
              run: |
                  echo "Changes since ${{ steps.changes.outputs.last-tag }}:"
                  echo "${{ steps.changes.outputs.log }}"

            - if: steps.new.outputs.init == 'true'
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "${{ steps.version.outputs.VERSION }}"
                  prerelease: false

            - if: steps.new.outputs.init == 'true'
              id: release
              uses: cardinalby/git-get-release-action@v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  tag: "${{ steps.version.outputs.VERSION }}"

            - if: steps.new.outputs.init == 'true'
              uses: irongut/EditRelease@v1.2.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  id: ${{ steps.release.outputs.id }}
                  body: "# ${{ steps.version.outputs.VERSION }}\n## Changelog\nThese are the changes since version ${{ steps.changes.outputs.last-tag }}:\n${{ steps.changes.outputs.log }}\n## Installation command\n`pipx install https://github.com/PaddeCraft/BackUpUtility/archive/refs/tags/${{ steps.version.outputs.VERSION }}.zip`"
